# Generated by Django 3.1 on 2020-11-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('model', models.CharField(max_length=200)),
                ('price', models.FloatField(max_length=200)),
                ('mileage', models.FloatField(max_length=200)),
                ('power', models.IntegerField(max_length=200)),
                ('seat_num', models.IntegerField(max_length=200)),
            ],
        ),
    ]
