# Generated by Django 3.1 on 2020-11-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='mileage',
            new_name='engine_capacity',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='model',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='seat_num',
        ),
        migrations.AddField(
            model_name='cars',
            name='fuel',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='ground_clearance',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='tank_capacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='power',
            field=models.IntegerField(null=True),
        ),
    ]
