# Generated by Django 3.1 on 2020-11-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_auto_20201122_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
