# Generated by Django 3.1.3 on 2020-11-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='carname',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
