# Generated by Django 3.1.3 on 2020-11-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0011_auto_20201127_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_booked',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
