# Generated by Django 3.1.3 on 2020-12-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0012_auto_20201127_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='description',
            field=models.CharField(max_length=1500, null=True),
        ),
    ]
