# Generated by Django 3.1.3 on 2020-12-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0013_cars_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='description',
            field=models.TextField(max_length=1500, null=True),
        ),
    ]
