# Generated by Django 3.1.3 on 2020-12-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0014_auto_20201210_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='extras',
            field=models.TextField(max_length=1500, null=True),
        ),
    ]
